export type ElemProps = {
  elem: HTMLDivElement;
  elements?: HTMLDivElement[];
  width?: string;
  height?: string;
  x?: string;
  y?: string;
  zIndex?: string;
  borderWidth?: string;
  borderStyle?: string;
  borderRadius?: string;
  borderColor?: string;
  bgColor?: string;
  textContent?: string;
  containerColor?: string;
  transform?: string;
  fontFamily?: string;
  fontSize?: string;
  textDecoration?: string;
  fontWeight?: string;
  fontStyle?: string;
  textAlign?: string;
  textColor?: string;
};
